apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
spec:
  replicas: 3 
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: tomcat
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
        labels:
          # Important: these labels need to match the selector above
          # The api server enforces this constraint.
          app: tomcat
    spec:
      containers:
        - name: tomcat-server
          image: "manjula/tomcat:18-11-2015-17-03"
          ports:
            - containerPort: 8080
